# Versión de docker
version: '3.7'
services:
  # API Usuarios
  db-mysql:
    container_name: "mysql-container"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: usuarios
      MYSQL_DATABASE: usuarios
    ports:
      - "7070:3306"

  usuarios-server:
    build: ./Microservicio-Usuarios/docker
    container_name: usuarios-server
    ports:
      - "8383:8383"

  # API Productos-Servicios
  db-mariadb:
    container_name: "mariadb-container"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: productos
      MYSQL_USER: productos
      MYSQL_DATABASE: productos
      MYSQL_PASSWORD: productos
    ports:
      - "7071:3306"

  productos-servicios-server:
    build: ./Microservicio-Producto-Servicios/docker
    container_name: productos-servicios-server
    ports:
      - "8384:8384"

  # API Pedidos
  pedidos-server:
    build: ./Microservicio-Pedidos/docker
    container_name: pedidos-server
    ports:
      - "8385:8385"